# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Aaron John's Blog
email: aaron2nj@gmail.com
description: "Combo of AI and Mobile: Problems and Solutions"
topics: "on Artificial Neural Network's"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://aaronjohn2.github.io" # the base hostname & protocol for your site
twitter_username: aaron2john
github_username:  aaronjohn2

# Build settings
#markdown: redcarpet
markdown: kramdown
future: false
